### ISSUE TITLE
Internal Server error 

### ISSUE THREAD

**Issue by dermitdemwolf** [hicknhack-software/redmine_hourglass#118]
Hi,
I would love to use the plugin, but I get always the following error:

`Completed 500 Internal Server Error in 605ms (ActiveRecord: 13.1ms)

ActionView::Template::Error (undefined method `hourglass_time_tracker' for #<User:0x00005576951b16e0>):
    1: - if Hourglass::SettingsStorage[:global_tracker]
    2:   - time_tracker = User.current.hourglass_time_tracker
    3:   - if time_tracker
    4:     = render partial: 'hooks/time_tracker/stop_link', locals: {time_tracker: time_tracker, issue: nil}
    5:     - if time_tracker.project.present? && time_tracker.activity.blank?
  plugins/redmine_hourglass/app/views/hooks/_account_menu_link.slim:2:in `_plugins_redmine_hourglass_app_views_hooks__account_menu_link_slim__2704841100015342659_46983861996440'
  plugins/redmine_hourglass/lib/hourglass/redmine_hooks.rb:26:in `view_layouts_base_content'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:108:in `_app_views_layouts_base_html_erb__1393592602301009392_46983900949480'
  app/views/layouts/admin.html.erb:8:in `_app_views_layouts_admin_html_erb__2856875075915484298_46983898303060'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`
I tried already a lot. "Bundle install" works fine. No conflicts there.
We use Redmine 3.4.5.
Maybe somebody out there has an idea?
Thank you very much

**Comment by arBmind** [comment]
might be related with #123 - you might try the same workaround (use old code before Redmine 4.0.x support)
