### ISSUE TITLE
undefined method `hourglass_tab' for class

### ISSUE THREAD

**Issue by radist** [hicknhack-software/redmine_hourglass#123]
```
I, [2019-04-19T01:16:57.382346 #3657]  INFO -- :   Rendered projects/settings.html.erb within layouts/base (70.5ms)
I, [2019-04-19T01:16:57.382924 #3657]  INFO -- : Completed 500 Internal Server Error in 351ms (ActiveRecord: 25.7ms)
F, [2019-04-19T01:16:57.385091 #3657] FATAL -- : 
ActionView::Template::Error (undefined method `hourglass_tab' for class `#<Class:0x007fbc938d05c0>'):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:13:in `method'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/projects_helper_patch.rb:13:in `project_settings_tabs_with_hourglass'

```

**Comment by radist** [comment]
```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.2
  additionals                    2.0.0
  autowatch                      0.2.0
  clipboard_image_paste          1.12
  collapsed_journals             0.0.3
  custom_menu                    1.7.4
  issue_hot_buttons              0.4.4
  periodictask                   3.1.1
  progressive_projects_list      3.0.1
  projects_show                  0.0.3
  redmine__select2               1.1.0
  redmine_agile                  1.4.2
  redmine_attach_by_url          1.0.2
  redmine_autoclose              0.0.4
  redmine_bitbucket              1.0.0
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_codebutton             0.1.0
  redmine_contacts               4.1.1
  redmine_contacts_helpdesk      3.0.5
  redmine_contacts_invoices      4.1.1
  redmine_custom_css             0.1.6
  redmine_custom_js              0.1.0
  redmine_custom_workflows       0.1.6
  redmine_default_assign         0.6
  redmine_digest                 1.1.0
  redmine_editauthor             0.11.0
  redmine_email_images           0.2.0
  redmine_finance                2.1.0
  redmine_gist                   0.1.0
  redmine_gitlab_hook            0.1.3
  redmine_hourglass              1.1.1
  redmine_impersonate            1.0.0
  redmine_issue_completion       0.0.2
  redmine_issue_dynamic_edit     0.6.0
  redmine_issue_favicon          0.0.1
  redmine_issue_history_filter   0.0.1
  redmine_issue_templates        0.1.3
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_images   0.3.1
  redmine_keyboard_shortcuts     0.0.1
  redmine_knowledgebase          3.2.1
  redmine_leaves                 0.1.0
  redmine_lightbox2              0.3.1
  redmine_login_audit            0.3.2
  redmine_macros                 0.0.1
  redmine_mail_reminder          3.0.0.0001
  redmine_mentions               0.0.1
  redmine_move_comments          0.0.2
  redmine_my_page                0.1.10
  redmine_one_issue_in_process_only 0.0.4
  redmine_openid_provider        1.0.0
  redmine_people                 1.2.0
  redmine_percent_done           1.1.0
  redmine_project_alias_2        1.0.2
  redmine_recurring_tasks        0.0.2
  redmine_scheduling_poll        2.0.0
  redmine_send_to_contacts       0.0.1
  redmine_shared_api             0.0.2
  redmine_sidekiq                2.1.0
  redmine_silencer               0.4.1
  redmine_slack                  0.2
  redmine_spent_time             3.1.2
  redmine_spent_time_curve       0.0.1
  redmine_tags                   3.2.0
  redmine_theme_changer          0.2.0
  redmine_webhook                0.0.2
  redmine_workflow_hidden_fields 0.3.0
  redmine_workload               0.0.1
  sidebar_hide                   0.0.7
  subtask_list_columns           0.0.3
  that_email_log                 0.0.1
  that_issue_reply_button        0.0.1
  ttm                            0.2.0
  unread_issues                  2.1.0
  vault                          0.3.9
```

**Comment by cs42** [comment]
I'm on Redmine 3.4.10 and have the same problem. To solve it I replaced lib/hourglass/redmine_patches/projects_helper_path.rb with with the file from af3ce2a

**Comment by arBmind** [comment]
This might be a regression from our Redmine 4.0.x support. It requires further investigations.
