### ISSUE TITLE
Internal Server Error in 10965ms (ActiveRecord: 471.2ms)

### ISSUE THREAD

**Issue by Girmiti2its** [hicknhack-software/redmine_hourglass#130]
Hi 
I get the below error on Redmine 4.0.5 version. I tried latest src as well as old releases.

plugins/redmine_hourglass/app/models/hourglass/time_booking_query.rb:40:in `block in initialize_available_filters'
plugins/redmine_hourglass/app/models/hourglass/time_booking_query.rb:39:in `each'
plugins/redmine_hourglass/app/models/hourglass/time_booking_query.rb:39:in `initialize_available_filters'
app/models/query.rb:615:in `available_filters'
app/models/query.rb:625:in `add_filter'
plugins/redmine_hourglass/app/controllers/concerns/hourglass_ui/overview.rb:24:in `index_page_list_arguments'
plugins/redmine_hourglass/app/controllers/concerns/hourglass_ui/overview.rb:17:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Please let me know how to fix this issue.

Thanks in advance.

**Comment by Girmiti2its** [comment]
I have commented out the below line under funcation def initialize_available_filters
      # we need fix the last added filters cause redmine fucks up the name
      #available_filters.select { |k, _| k.start_with? 'time_entry' }.each do |_, v|
      #  v[:name] = v[:field].name
      #end

Then internal server Error vanished and i am able to view the tabs from top menu.
