### ISSUE TITLE
Can't bulk edit multiple issues

### ISSUE THREAD

**Issue by philhq** [hicknhack-software/redmine_hourglass#16]
Hi there,

On the issues view I can no longer right click when selecting multiple issues.

```
ActionView::Template::Error (undefined method `id' for nil:NilClass):
     6:       = render partial: 'hooks/time_tracker/activity_dialog_content', locals: {time_tracker: time_tracker}
     7: - elsif authorize_globally_for 'hourglass/time_trackers', 'start'
     8:   li
     9:     = render partial: 'hooks/time_tracker/start_link', locals: {time_tracker: time_tracker, issue: @issue, time_tracker_data: {params: {time_tracker: {issue_id: @issue.id}}}}
    10:     - if time_tracker
    11:       = render partial: 'hooks/time_tracker/start_dialog_content', locals: {time_tracker: time_tracker, issue: nil}
  plugins/redmine_hourglass/app/views/hooks/_issue_actions.slim:9:in `_plugins_redmine_hourglass_app_views_hooks__issue_actions_slim___3435038388682183672_17379975760'
  plugins/redmine_hourglass/lib/hourglass/redmine_hooks.rb:9:in `view_issues_context_menu_start'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/context_menus/issues.html.erb:2:in `_app_views_context_menus_issues_html_erb__929771240315758382_17381649020'
  app/controllers/context_menus_controller.rb:58:in `issues'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by philhq** [comment]
Thank you! :)
