### ISSUE TITLE
bundle exec rake db error.

### ISSUE THREAD

**Issue by archonwang** [hicknhack-software/redmine_hourglass#29]
@jume-dev , please check it. Thanks.
my environment is 
```
Environment:
  Redmine version                3.3.3.stable.16680
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

error log

```
[root@jira redmine-3.3]# bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=Hourglass
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/opt/redmine-3.3/config/application.rb:5:in `<top (required)>'
/opt/redmine-3.3/Rakefile:5:in `require'
/opt/redmine-3.3/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/opt/redmine-3.3/config/application.rb:5:in `<top (required)>'
/opt/redmine-3.3/Rakefile:5:in `require'
/opt/redmine-3.3/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by jume-dev** [comment]
Looks like a problem with your gems. I assume you did bundle install before?

**Comment by archonwang** [comment]
@jume-dev ,yes. anything I have done wrong?

**Comment by jume-dev** [comment]
Nah, let me think.
Could it be that you don't have an js interpreter installed? Something like nodejs?
I guess not, take a look on [this](https://github.com/sstephenson/execjs) and install an appropriate js interpreter, maybe therubyracer game would be good.

**Comment by jume-dev** [comment]
master now contains the rubyracer.
do bundle install and try again pls

**Comment by archonwang** [comment]
@jume-dev 
Nice. it Worked, by the way , any instruction about how to use the plugin? 
Thanks.

**Comment by jume-dev** [comment]
We have plenty of information available in the readme and in the wiki, please take a look there
