### ISSUE TITLE
bundle exec rake redmine:plugins:hourglass:api_docs  occured error

### ISSUE THREAD

**Issue by archonwang** [hicknhack-software/redmine_hourglass#31]
@jume-dev 
please check it please. 
My environment is redmine-3.3 without development and test database.
Thanks.

the error log is

```
[root@jira redmine-3.3]# bundle exec rake redmine:plugins:hourglass:api_docs RAILS_ENV=production
/usr/local/rvm/rubies/ruby-2.2.4/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib:/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-support-3.6.0/lib /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/exe/rspec --pattern /opt/redmine-3.3/plugins/redmine_hourglass/spec/integration/\*\*/\*_spec.rb -I/opt/redmine-3.3/plugins/redmine_hourglass/spec --format Rswag::Specs::SwaggerFormatter --order defined
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection': 'test' database is not configured. Available: ["production"] (ActiveRecord::AdapterNotSpecified)
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/base.rb:26:in `<top (required)>'
	from /opt/redmine-3.3/lib/plugins/acts_as_activity_provider/init.rb:2:in `block in <top (required)>'
	from /opt/redmine-3.3/config/initializers/00-core_plugins.rb:12:in `eval'
	from /opt/redmine-3.3/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
	from /opt/redmine-3.3/config/initializers/00-core_plugins.rb:2:in `each'
	from /opt/redmine-3.3/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	from /opt/redmine-3.3/config/environment.rb:14:in `<top (required)>'
	from /opt/redmine-3.3/test/test_helper.rb:28:in `require'
	from /opt/redmine-3.3/test/test_helper.rb:28:in `<top (required)>'
	from /opt/redmine-3.3/plugins/redmine_hourglass/spec/spec_helper.rb:7:in `require'
	from /opt/redmine-3.3/plugins/redmine_hourglass/spec/spec_helper.rb:7:in `<top (required)>'
	from /opt/redmine-3.3/plugins/redmine_hourglass/spec/swagger_helper.rb:1:in `require_relative'
	from /opt/redmine-3.3/plugins/redmine_hourglass/spec/swagger_helper.rb:1:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rswag-specs-1.3.0/lib/rswag/specs/swagger_formatter.rb:2:in `require'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rswag-specs-1.3.0/lib/rswag/specs/swagger_formatter.rb:2:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:227:in `require'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:227:in `rescue in custom_formatter'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:224:in `custom_formatter'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:177:in `find_formatter'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/formatters.rb:146:in `add'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:876:in `add_formatter'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:117:in `block in load_formatters_into'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:117:in `each'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:117:in `load_formatters_into'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:23:in `configure'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
	from /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.4/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/lib:/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-support-3.6.0/lib /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rspec-core-3.6.0/exe/rspec --pattern /opt/redmine-3.3/plugins/redmine_hourglass/spec/integration/\*\*/\*_spec.rb -I/opt/redmine-3.3/plugins/redmine_hourglass/spec --format Rswag::Specs::SwaggerFormatter --order defined failed

```

**Comment by jume-dev** [comment]
Alright, please take a moment to read the error messages yourself, before posting them here. If you add an better problem description, i can help yourself faster.
> 'test' database is not configured
You don't have a test database, calling `rake db:migrate RAILS_ENV=test` and `rake redmine:plugins:migrate RAILS_ENV=test` should fix that

**Comment by archonwang** [comment]
Thanks, I will try it.
