### ISSUE TITLE
/hourglass/ui  500 Internal error

### ISSUE THREAD

**Issue by radist** [hicknhack-software/redmine_hourglass#52]
```
F, [2017-10-02T18:26:34.562850 #23866] FATAL -- : 
ActionView::Template::Error (undefined method `allowed_to_one_of' for #<Project::ActiveRecord_Associations_CollectionProxy:0x007ff72d60a550>):
    2:   .label
    3:     = form.label :project_id
    4:   .input
    5:     = form.select :project_id, projects_for_project_select(entry.project), {include_blank: !local_assigns[:required]}, disabled: local_assigns[:disabled], required: local_assigns[:required]
  plugins/redmine_hourglass/app/helpers/hourglass/application_helper.rb:34:in `projects_for_project_select'
  plugins/redmine_hourglass/app/views/hourglass_ui/forms/fields/_project.slim:5:in `_af0575edb6ca94056539da729659389a'
  plugins/redmine_hourglass/app/helpers/hourglass/application_helper.rb:26:in `form_field'
  plugins/redmine_hourglass/app/views/hourglass_ui/_time_tracker_control.slim:29:in `block in _5c581915433df9daee0b2694130af5a7'
  plugins/redmine_hourglass/app/views/hourglass_ui/_time_tracker_control.slim:13:in `_5c581915433df9daee0b2694130af5a7'
  plugins/redmine_hourglass/app/views/hourglass_ui/index.slim:6:in `block in _0d2598967b3910ec1890d3b78dc8a030'
  plugins/redmine_hourglass/app/views/hourglass_ui/layouts/_hourglass.slim:20:in `_984c8041fab82944f1b213b860764032'
  plugins/redmine_hourglass/app/views/hourglass_ui/index.slim:1:in `_0d2598967b3910ec1890d3b78dc8a030'
```

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
```

**Comment by jume-dev** [comment]
That's weird. Do you have any other plugins installed? If so, please remove them temporary and try again. If it works, please report which plugin cause the trouble and i try to fix it

**Comment by xstable** [comment]
I'm not a redmine-crack. So tell me how to remove such plugins... and questions is, does I keep my data of those plugins?
It's a LIVE-System, so I can not risk the data collected there.
Please give a hint.

**Comment by jume-dev** [comment]
Wait, you are not OP, are you guys connected?

But anyways, to remove plugins simply remove the folder from the plugin directory (by copying it somewhere else). That should normally not result in data loss as the database is not affected by this.

For live systems it's probably always advisable to create a backup before messing with anything on it.

_Just a note: If you need extended support with redmine problems, feel free to contact us on https://www.hicknhack-software.com/contact._
