### ISSUE TITLE
Error since today if stopping TimeTracker

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_hourglass#77]
My Enviroment: 

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.7-p456 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Mercurial                      2.2.2
  Bazaar                         2.1.1
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.9
  redmine_hourglass              1.0.0
  redmine_local_avatars          1.0.3
  redmine_move_comments          0.0.2
  redmine_people                 1.3.2
  sidebar_hide                   0.0.8

This is the error: 

```
Started DELETE "/hourglass/time_trackers/155/stop" for 2a02:908:e940:5c1c:129f:546a:146e:934 at 2018-06-11 18:05:37 +0200
Processing by Hourglass::TimeTrackersController#stop as JS
  Parameters: {"id"=>"155"}
  Current user: admin (id=1)
divided by 0
/home/suther/redmine/plugins/redmine_hourglass/lib/hourglass/date_time_calculations.rb:36:in `%'
/home/suther/redmine/plugins/redmine_hourglass/lib/hourglass/date_time_calculations.rb:36:in `round_interval'
/home/suther/redmine/plugins/redmine_hourglass/lib/hourglass/date_time_calculations.rb:46:in `calculate_bookable_time'
/home/suther/redmine/plugins/redmine_hourglass/lib/hourglass/date_time_calculations.rb:54:in `booking_process'
/home/suther/redmine/plugins/redmine_hourglass/app/models/hourglass/time_log.rb:53:in `book'
/home/suther/redmine/plugins/redmine_hourglass/app/models/hourglass/time_tracker.rb:35:in `block in stop'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:277:in `transaction'
/home/suther/redmine/plugins/redmine_hourglass/app/models/hourglass/time_tracker.rb:31:in `stop'
/home/suther/redmine/plugins/redmine_hourglass/app/controllers/hourglass/time_trackers_controller.rb:36:in `block in stop'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/transactions.rb:277:in `transaction'
/home/suther/redmine/plugins/redmine_hourglass/app/controllers/hourglass/time_trackers_controller.rb:35:in `stop'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/home/suther/redmine/plugins/redmine_hourglass/app/controllers/hourglass/api_base_controller.rb:56:in `block in catch_halt'
/home/suther/redmine/plugins/redmine_hourglass/app/controllers/hourglass/api_base_controller.rb:55:in `catch'
/home/suther/redmine/plugins/redmine_hourglass/app/controllers/hourglass/api_base_controller.rb:55:in `catch_halt'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/home/suther/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/home/suther/redmine/vendor/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/home/suther/redmine/vendor/bundle/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/home/suther/redmine/vendor/bundle/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/home/suther/redmine/vendor/bundle/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/suther/redmine/vendor/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/home/suther/redmine/vendor/bundle/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/home/suther/redmine/vendor/bundle/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/home/suther/redmine/vendor/bundle/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
/home/suther/redmine/vendor/bundle/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
/home/suther/redmine/vendor/bundle/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
/home/suther/redmine/vendor/bundle/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:142:in `start'
/home/suther/redmine/vendor/bundle/gems/unicorn-5.3.0/bin/unicorn_rails:209:in `<top (required)>'
/home/suther/redmine/vendor/bundle/bin/unicorn_rails:23:in `load'
/home/suther/redmine/vendor/bundle/bin/unicorn_rails:23:in `<top (required)>'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:75:in `load'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:75:in `kernel_load'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli/exec.rb:28:in `run'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:424:in `exec'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:27:in `dispatch'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/cli.rb:18:in `start'
/package/host/localhost/ruby-2.3/bin/bundle:30:in `block in <main>'
/package/host/localhost/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/package/host/localhost/ruby-2.3/bin/bundle:22:in `<main>'
Completed 500 Internal Server Error in 82ms (Views: 0.6ms | ActiveRecord: 29.4ms)
```

**Comment by xstable** [comment]
I fixed it.
I've created an new Project today.
It was, because in hourglas-config I add 0,25 instead of 0.25.
![auswahl_808](https://user-images.githubusercontent.com/1778068/41243740-3bd97926-6da3-11e8-9a7f-8865431429f6.jpg)

Think you should catch this error and output an usable Error-Message for Users

**Comment by jume-dev** [comment]
Alright, thanks for reporting and finding and reporting again. Gonna be put on the list of things to fix
