### ISSUE TITLE
Server error when opening /hourglass/ui/time_bookings

### ISSUE THREAD

**Issue by hameno** [hicknhack-software/redmine_hourglass#96]
```
Started GET "/hourglass/ui/time_bookings" for <IP> at 2018-12-07 10:41:22 +0100
Processing by HourglassUiController#time_bookings as HTML
  Current user: <USER> (id=3)
  Rendered plugins/redmine_hourglass/app/views/hourglass_ui/lists/_chart.slim (8.6ms)
  Rendered plugins/redmine_hourglass/app/views/hourglass_ui/time_bookings.slim within layouts/base (9.0ms)
Completed 500 Internal Server Error in 1550ms (ActiveRecord: 126.7ms)

ActionView::Template::Error (divided by 0):
    1: - data, ticks, tooltips = chart_data @chart_query
    2: javascript:
    3:   window.hourglass = window.hourglass || {};
    4:   window.hourglass.jqplotData = {
  plugins/redmine_hourglass/lib/hourglass/date_time_calculations.rb:36:in `round_interval'
  plugins/redmine_hourglass/app/helpers/hourglass/list_helper.rb:106:in `rounded_total'
  plugins/redmine_hourglass/app/helpers/hourglass/list_helper.rb:100:in `block in time_booking_total'
  plugins/redmine_hourglass/app/helpers/hourglass/list_helper.rb:99:in `each'
  plugins/redmine_hourglass/app/helpers/hourglass/list_helper.rb:99:in `reduce'
  plugins/redmine_hourglass/app/helpers/hourglass/list_helper.rb:99:in `time_booking_total'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:40:in `block (2 levels) in hours_per_date'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:40:in `each'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:40:in `map'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:40:in `block in hours_per_date'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:37:in `hours_per_date'
  plugins/redmine_hourglass/app/helpers/hourglass/chart_helper.rb:11:in `chart_data'
  plugins/redmine_hourglass/app/views/hourglass_ui/lists/_chart.slim:1:in `_plugins_redmine_hourglass_app_views_hourglass_ui_lists__chart_slim__3144328911474596236_70045326962100'
  plugins/redmine_hourglass/app/views/hourglass_ui/time_bookings.slim:2:in `block in _plugins_redmine_hourglass_app_views_hourglass_ui_time_bookings_slim___602535456053159714_70045358121700'
  plugins/redmine_hourglass/app/views/hourglass_ui/time_bookings.slim:1:in `_plugins_redmine_hourglass_app_views_hourglass_ui_time_bookings_slim___602535456053159714_70045358121700'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by arBmind** [comment]
Looks like you try to round to zero. This should be at least one.

**Comment by hameno** [comment]
What do you mean? Minimum time interval? This is set to 0.25 hours (as by default?).

**Comment by hameno** [comment]
@arBmind Can you explain what you mean? I did not do anything, it was like this right after the install.

**Comment by arBmind** [comment]
This was just a guess from the dump you posted.
`date_time_calculations.rb:36:in 'round_interval'` and `(divided by 0):`

I glimpsed at the code back then, but could not see what was happening to get this error.

@hameno Please provide some more details. Do you have hours tracked? Do you have any filters active?

**Comment by hameno** [comment]
We have thousands of hours tracked already before installing this plugin. 
What do you mean by filters?

**Comment by arBmind** [comment]
I added some protection around this error. I could not really test this scenario.

@hameno Please give the latest revision a try if you can.

**Comment by hameno** [comment]
👍 Looks good
